## Sitewide settings ##
baseURL: https://rsdc-new.netlify.app/
relativeURLs: true
languageCode: en-us
title: Remy Sheppard
googleAnalytics: G-CQYCG8XPGL

## Parameters
params:
  description: Remy Sheppard is a Christian, web developer, and animal welfare advocate from Fayetteville, North Carolina.

## Hugo Settings
buildFuture: false
enableGitInfo: true
enableRobotsTXT: true
paginate: 9
timezone: America/New_York

## Markup Settings
markup:
  highlight:
    style: manni
    tabWidth: 2

## Taxonomies
taxonomies:
  category: categories
  tag: tags

## Related Categories
related:
  includeNewer: true
  threshold: 80
  toLower: false
  indices:
  - name: categories
    weight: 100

## Menus
menu:
  social:
  - identifier: about
    name: About
    pre: <i class="fa-duotone fa-user-astronaut fa-fw fa-xl"></i>
    url: /about
    weight: 2

  - identifier: code
    name: Hire Me
    pre: <i class="fa-duotone fa-code fa-fw fa-xl"></i>
    url: mailto:me@remysheppard.com
    weight: 1

  - identifier: facebook
    name: Facebook
    pre: <i class="fab fa-facebook fa-fw fa-xl"></i>
    url: https://www.facebook.com/remy.sheppard.websites
    weight: 3

  - identifier: instagram
    name: Instagram
    pre: <i class="fab fa-instagram fa-fw fa-xl"></i>
    url: https://www.instagram.com/bloodconquered
    weight: 4

  - identifier: YouTube
    name: YouTube
    pre: <i class="fab fa-youtube fa-fw fa-xl"></i>
    url: https://www.youtube.com/channel/UCO5DfukQ3M96m6GGlcIcPvg
    weight: 6

  - identifier: twitter
    name: Twitter
    pre: <i class="fab fa-twitter fa-fw fa-xl"></i>
    url: https://www.twitter.com/bloodconquered
    weight: 5

  - identifier: LinkedIn
    name: LinkedIn
    pre: <i class="fab fa-linkedin fa-fw fa-xl"></i>
    url: https://www.linkedin.com/in/bloodconquered/
    weight: 7